/**
 * Graph-corpus JSON dataset descriptor and writer (G1a).
 *
 * @remarks
 * Defines the graph-corpus-specific content for the three-file JSON dataset
 * pattern (`data.json`, `types.ts`, `index.ts`) and delegates the mechanical
 * write to {@link writeJsonDataset}.
 *
 * Unlike the older per-dataset descriptors, the emitted `types.ts` does NOT
 * duplicate the corpus interfaces: the types are defined once in
 * {@link generateGraphCorpusData}'s module (the single source of truth) and the
 * emitted `types.ts` re-exports them, so no hand-maintained type runs parallel
 * to the generated corpus (Decision A / ADR-031).
 */
import type { Logger } from '@oaknational/logger';

import type { GraphCorpus } from './graph-corpus-generator.js';
import { writeJsonDataset, type JsonDatasetDescriptor } from './write-json-dataset.js';

const graphCorpusTypesModuleLines: readonly string[] = [
  '/**',
  ' * Type definitions for the graph corpus.',
  ' *',
  ' * @remarks',
  ' * Generated by the graph corpus JSON writer. The corpus types are defined',
  ' * once in the generator (the single source of truth) and re-exported here,',
  ' * so no hand-maintained type runs parallel to the generated corpus',
  ' * (Decision A / ADR-031).',
  ' */',
  '',
  'export type {',
  '  GraphCorpus,',
  '  GraphCorpusUnitNode,',
  '  GraphCorpusEdge,',
  '  GraphCorpusNodeId,',
  '  GraphCorpusStats,',
  '  GraphCorpusDroppedEdge,',
  "} from '../../../bulk/generators/graph-corpus-generator.js';",
  '',
];

const graphCorpusIndexModuleLines: readonly string[] = [
  '/**',
  ' * Graph corpus — typed loader for generated JSON data.',
  ' *',
  ' * @remarks',
  ' * Generated by the graph corpus JSON writer. Imports raw JSON data and',
  ' * re-exports it with the generator-owned TypeScript interfaces, validating',
  ' * the kind-qualified node ids and edge type literals at load (ADR-086',
  ' * union-literal narrowing).',
  ' */',
  "import { createRequire } from 'node:module';",
  '',
  'import type {',
  '  GraphCorpus,',
  '  GraphCorpusEdge,',
  '  GraphCorpusNodeId,',
  '  GraphCorpusStats,',
  '  GraphCorpusUnitNode,',
  '  GraphCorpusDroppedEdge,',
  "} from './types.js';",
  '',
  'const require = createRequire(import.meta.url);',
  "const data: JsonGraphCorpus = require('./data.json');",
  '',
  'interface JsonGraphCorpusNode {',
  '  readonly id: string;',
  '  readonly unitSlug: string;',
  '  readonly unitTitle: string;',
  '  readonly subject: string;',
  '  readonly keyStage: string;',
  '  readonly year?: number;',
  '  readonly priorKnowledge: readonly string[];',
  '  readonly threadSlugs: readonly string[];',
  '}',
  '',
  'interface JsonGraphCorpusEdge {',
  '  readonly source: string;',
  '  readonly type: string;',
  '  readonly target: string;',
  '}',
  '',
  'interface JsonGraphCorpus {',
  '  readonly version: string;',
  '  readonly generatedAt: string;',
  '  readonly sourceVersion: string;',
  '  readonly stats: GraphCorpusStats;',
  '  readonly nodes: readonly JsonGraphCorpusNode[];',
  '  readonly edges: readonly JsonGraphCorpusEdge[];',
  '  readonly droppedEdges: readonly GraphCorpusDroppedEdge[];',
  '  readonly seeAlso: string;',
  '}',
  '',
  '/** Narrows a raw string to a kind-qualified unit node id. */',
  'function isUnitNodeId(value: string): value is GraphCorpusNodeId {',
  "  return value.startsWith('unit:');",
  '}',
  '',
  'function toUnitNodeId(value: string): GraphCorpusNodeId {',
  '  if (!isUnitNodeId(value)) {',
  '    throw new TypeError(`Unexpected graph-corpus node id (missing "unit:" prefix): ${value}`);',
  '  }',
  '  return value;',
  '}',
  '',
  'function createNode(node: JsonGraphCorpusNode): GraphCorpusUnitNode {',
  '  return {',
  '    id: toUnitNodeId(node.id),',
  '    unitSlug: node.unitSlug,',
  '    unitTitle: node.unitTitle,',
  '    subject: node.subject,',
  '    keyStage: node.keyStage,',
  '    year: node.year,',
  '    priorKnowledge: node.priorKnowledge,',
  '    threadSlugs: node.threadSlugs,',
  '  };',
  '}',
  '',
  'function createEdge(edge: JsonGraphCorpusEdge): GraphCorpusEdge {',
  "  if (edge.type !== 'prerequisiteFor') {",
  '    throw new TypeError(`Unexpected graph-corpus edge type: ${edge.type}`);',
  '  }',
  '  return {',
  '    source: toUnitNodeId(edge.source),',
  '    type: edge.type,',
  '    target: toUnitNodeId(edge.target),',
  '  };',
  '}',
  '',
  'function createGraphCorpus(graph: JsonGraphCorpus): GraphCorpus {',
  '  return {',
  '    version: graph.version,',
  '    generatedAt: graph.generatedAt,',
  '    sourceVersion: graph.sourceVersion,',
  '    stats: graph.stats,',
  '    nodes: graph.nodes.map(createNode),',
  '    edges: graph.edges.map(createEdge),',
  '    droppedEdges: graph.droppedEdges,',
  '    seeAlso: graph.seeAlso,',
  '  };',
  '}',
  '',
  '/**',
  ' * The bulk curriculum graph corpus (unit nodes + prerequisiteFor edges).',
  ' *',
  ' * @remarks',
  ' * One identity space surfaced through bounded query views (Decision A). Node',
  ' * ids are kind-qualified (`unit:<unitSlug>`); edge endpoints reference those',
  ' * ids; the corpus has zero dangling endpoints, so it constructs in',
  ' * `createGraphView` without throwing.',
  ' */',
  'export const graphCorpus: GraphCorpus = createGraphCorpus(data);',
  '',
  'export type {',
  '  GraphCorpus,',
  '  GraphCorpusEdge,',
  '  GraphCorpusNodeId,',
  '  GraphCorpusStats,',
  '  GraphCorpusUnitNode,',
  '  GraphCorpusDroppedEdge,',
  "} from './types.js';",
  '',
];

/**
 * Graph-corpus dataset descriptor.
 *
 * @remarks
 * Provides the graph-corpus-specific (re-exporting) types and typed loader
 * content for the generic JSON dataset writer.
 */
export const graphCorpusDescriptor: JsonDatasetDescriptor = {
  directoryName: 'graph-corpus',
  typesModuleContent: graphCorpusTypesModuleLines.join('\n'),
  indexModuleContent: graphCorpusIndexModuleLines.join('\n'),
};

/**
 * Writes the graph corpus output as JSON plus typed TypeScript modules.
 *
 * @param corpus - Graph corpus to write
 * @param outputDir - Parent output directory
 * @returns Path to the created `graph-corpus` directory
 */
export async function writeGraphCorpusAsJson(
  corpus: GraphCorpus,
  outputDir: string,
  logger?: Logger,
): Promise<string> {
  logger?.info('bulk.writer.write_graph_corpus_json', {
    outputDir,
    sourceVersion: corpus.sourceVersion,
  });
  return writeJsonDataset(graphCorpusDescriptor, corpus, outputDir, logger);
}
