/**
 * Utility for writing generated graph data to TypeScript files.
 *
 * @remarks
 * Handles serialization of graph data structures to TypeScript format
 * with proper `as const` annotations and TSDoc comments.
 */
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import type { Logger } from '@oaknational/logger';
import type { ThreadProgressionGraph } from './thread-progression-generator.js';

/**
 * Escapes a string for use in TypeScript string literals.
 */
function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Generates the file header with TSDoc.
 */
function generateHeader(graph: ThreadProgressionGraph): readonly string[] {
  return [
    '/**',
    ' * Thread Progression Graph — extracted from bulk download data.',
    ' *',
    ' * @remarks',
    ' * - Generated by `pnpm vocab-gen`',
    ` * - Source: ${graph.sourceVersion}`,
    ` * - Generated: ${graph.generatedAt}`,
    ' * - Contains ordered unit sequences within curriculum threads',
    ' * - Use for learning path recommendations and progression queries',
    ' *',
    ' * @see ADR-086 for extraction methodology',
    ' * @see property-graph-data.ts for the graph pattern',
    ' */',
    '',
  ];
}

/**
 * Generates the export TSDoc.
 */
function generateExportDoc(graph: ThreadProgressionGraph): readonly string[] {
  const { threadCount } = graph.stats;
  const subjectCount = graph.stats.subjectsCovered.length;

  return [
    '/**',
    ' * Thread progression graph with ordered unit sequences.',
    ' *',
    ' * @remarks',
    ` * Contains ${threadCount} threads across ${subjectCount} subjects.`,
    ' * Threads show conceptual progressions across years (e.g., "Number: Fractions" from Year 2-6).',
    ' *',
    ' * Use this to answer questions like:',
    ' * - "What\'s the learning path for fractions?"',
    ' * - "What comes after this unit in the thread?"',
    ' * - "Which threads cover algebra?"',
    ' */',
  ];
}

/**
 * Serializes a single thread node.
 */
function serializeThread(thread: ThreadProgressionGraph['threads'][number]): readonly string[] {
  const firstYearValue = thread.firstYear === undefined ? 'undefined' : thread.firstYear;
  const lastYearValue = thread.lastYear === undefined ? 'undefined' : thread.lastYear;

  return [
    '    {',
    `      slug: '${thread.slug}',`,
    `      title: '${escapeString(thread.title)}',`,
    `      subjects: ${JSON.stringify(thread.subjects)},`,
    `      firstYear: ${firstYearValue},`,
    `      lastYear: ${lastYearValue},`,
    `      unitCount: ${thread.unitCount},`,
    `      units: ${JSON.stringify(thread.units)},`,
    '    },',
  ];
}

/**
 * Generates the graph body with metadata and threads.
 */
function generateGraphBody(graph: ThreadProgressionGraph): readonly string[] {
  return [
    'export const threadProgressionGraph = {',
    `  version: '${graph.version}',`,
    `  generatedAt: '${graph.generatedAt}',`,
    `  sourceVersion: '${graph.sourceVersion}',`,
    '',
    '  stats: {',
    `    threadCount: ${graph.stats.threadCount},`,
    `    subjectsCovered: ${JSON.stringify(graph.stats.subjectsCovered)},`,
    '  },',
    '',
    '  threads: [',
    ...graph.threads.flatMap(serializeThread),
    '  ],',
    '',
    `  seeAlso: '${escapeString(graph.seeAlso)}',`,
    '} as const;',
    '',
  ];
}

/**
 * Generates the derived type exports.
 */
function generateTypeExports(): readonly string[] {
  return [
    '/**',
    ' * Type representing the complete thread progression graph.',
    ' */',
    'export type ThreadProgressionGraph = typeof threadProgressionGraph;',
    '',
    '/**',
    ' * Type representing a thread slug in the graph.',
    ' */',
    "export type ThreadSlug = ThreadProgressionGraph['threads'][number]['slug'];",
    '',
  ];
}

/**
 * Serializes a ThreadProgressionGraph to TypeScript source code.
 *
 * @param graph - The graph data to serialize
 * @returns TypeScript source code string
 */
export function serializeThreadProgressionGraph(graph: ThreadProgressionGraph): string {
  const lines: string[] = [
    ...generateHeader(graph),
    ...generateExportDoc(graph),
    ...generateGraphBody(graph),
    ...generateTypeExports(),
  ];

  return lines.join('\n');
}

/**
 * Writes a thread progression graph to a TypeScript file.
 *
 * @param graph - The graph data to write
 * @param outputDir - Directory to write the file to
 * @returns Path to the written file
 */
export async function writeThreadProgressionFile(
  graph: ThreadProgressionGraph,
  outputDir: string,
  logger?: Logger,
): Promise<string> {
  logger?.info('bulk.writer.write_thread_progression_graph', {
    outputDir,
    sourceVersion: graph.sourceVersion,
  });
  const fileName = 'thread-progression-data.ts';
  const filePath = join(outputDir, fileName);
  const content = serializeThreadProgressionGraph(graph);

  await writeFile(filePath, content, 'utf-8');

  return filePath;
}
