/**
 * Re-runnable Oak Course generator — the Course-content arm of the canonical-export sync mechanism.
 * Extracts the course from the canonical export (`Oak Course.dc.html`, via `./course-extract`) and
 * emits the compile-time-validated typed module (`lib/course/oak-course.generated.ts`). Re-running it
 * on a fresh export is how Course content stays in sync by construction.
 *
 * Build tooling: lives in `scripts/` (never bundled by Next). Usage:
 * `pnpm tsx scripts/generate-course.ts`; `--check` verifies the committed module is up to date.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { extractScript, extractCourse, type RawCourse } from './course-extract';

const EXPORT_HTML = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../claude-design-canonical-export/Oak Course.dc.html',
);
const OUTPUT_MODULE = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../lib/course/oak-course.generated.ts',
);

/**
 * Render the emitted, compile-time-validated content module source.
 *
 * Emits TypeScript SOURCE (not JSON) deliberately: the `: Course` annotation on a source literal
 * makes tsc validate every block's discriminant against the `Block` union at build. A JSON import
 * would widen each block's `t` field to `string`, collapsing the discriminated-union check — so
 * "simplifying" this to emit `.json` + a typed import silently destroys the validation gate. Keep it
 * `.ts`. (The generated file is eslint-zoned for `max-lines` in `eslint.config.ts`.)
 */
export function emitModule(course: RawCourse): string {
  return `/**
 * Oak Course content — GENERATED by \`scripts/generate-course.ts\` from the Claude Design canonical
 * export (\`Oak Course.dc.html\`). Do not edit by hand: re-run the generator on a fresh export.
 *
 * The \`: Course\` annotation makes this a compile-time validation gate — a block that does not match
 * the \`Block\` union is a build error here, so the exhaustive \`BlockRenderer\` is safe by construction.
 */

import type { Course } from './types';

export const oakCourse: Course = ${JSON.stringify(course, null, 2)};
`;
}

/** Produce the module source from the export HTML string — the pure core (no IO). */
export function generateFromHtml(html: string): string {
  return emitModule(extractCourse(extractScript(html)));
}

/** Read the export and produce the module source (the IO shell; the `--check` CLI verifies freshness). */
export function generate(htmlPath: string = EXPORT_HTML): string {
  return generateFromHtml(readFileSync(htmlPath, 'utf8'));
}

function main(): void {
  const check = process.argv.includes('--check');
  const generated = generate();
  if (check) {
    const current = readFileSync(OUTPUT_MODULE, 'utf8');
    if (current !== generated) {
      throw new Error(
        `course generate --check: ${OUTPUT_MODULE} is stale; re-run \`pnpm tsx scripts/generate-course.ts\``,
      );
    }
    process.stdout.write('course generate --check: up to date\n');
    return;
  }
  writeFileSync(OUTPUT_MODULE, generated);
  process.stdout.write(`course generate: wrote ${OUTPUT_MODULE}\n`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
