/**
 * Re-runnable Oak Course generator — the Course-content arm of the canonical-export sync mechanism.
 * Extracts the course from the canonical export (`Oak Course.dc.html`, via `./course-extract`) and
 * emits the compile-time-validated typed module (`lib/course/oak-course.generated.ts`). Re-running it
 * on a fresh export is how Course content stays in sync by construction.
 *
 * Build tooling: lives in `scripts/` (never bundled by Next). Usage:
 * `pnpm tsx scripts/generate-course.ts`; `--check` verifies the committed module is up to date.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { extractScript, extractCourse, type LiteralValue, type RawCourse } from './course-extract';

const EXPORT_HTML = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../claude-design-canonical-export/Oak Course.dc.html',
);
const OUTPUT_MODULE = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../lib/course/oak-course.generated.ts',
);

/**
 * Render the emitted, compile-time-validated content module source.
 *
 * Emits TypeScript SOURCE (not JSON) deliberately: the `: Course` annotation on a source literal
 * makes tsc validate every block's discriminant against the `Block` union at build. A JSON import
 * would widen each block's `t` field to `string`, collapsing the discriminated-union check — so
 * "simplifying" this to emit `.json` + a typed import silently destroys the validation gate. Keep it
 * `.ts`. (The generated file is eslint-zoned for `max-lines` in `eslint.config.ts`.)
 */
export function emitModule(course: RawCourse): string {
  return `/**
 * Oak Course content — GENERATED by \`scripts/generate-course.ts\` from the Claude Design canonical
 * export (\`Oak Course.dc.html\`). Do not edit by hand: re-run the generator on a fresh export.
 *
 * The \`: Course\` annotation makes this a compile-time validation gate — a block that does not match
 * the \`Block\` union is a build error here, so the exhaustive \`BlockRenderer\` is safe by construction.
 */

import type { Course } from './types';

export const oakCourse: Course = ${JSON.stringify(course, null, 2)};
`;
}

/** Block fields the views render as `/${value}` — the shape contract this boundary protects. */
const ASSET_PATH_FIELDS = new Set(['href', 'src']);

/** Fail loud when one `href`/`src` field value is absolute or carries a URI scheme. */
function assertRelativeAssetPath(key: string, entry: LiteralValue, path: string): void {
  if (!ASSET_PATH_FIELDS.has(key) || typeof entry !== 'string') {
    return;
  }
  if (entry.startsWith('/') || /^[a-z][a-z0-9+.-]*:/i.test(entry)) {
    throw new Error(
      `course generate: ${path}.${key} = ${JSON.stringify(entry)} is not a relative asset path ` +
        '(the views render `/${' +
        key +
        '}`); fix the export content or extend this boundary deliberately',
    );
  }
}

/**
 * Asset-path boundary (strict-validation-at-boundary): every extracted `href`/`src` must be a
 * RELATIVE path — no leading slash, no URI scheme — because the views prefix `/` at render. An
 * absolute or protocol value in a fresh export would silently become a broken/protocol-relative
 * URL in the app, so it fails the GENERATE run loud instead, naming the field and value.
 */
export function assertRelativeAssetPaths(value: LiteralValue, path: string): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) => {
      assertRelativeAssetPaths(entry, `${path}[${index}]`);
    });
    return;
  }
  if (typeof value !== 'object' || value === null) {
    return;
  }
  for (const [key, entry] of Object.entries(value)) {
    assertRelativeAssetPath(key, entry, path);
    assertRelativeAssetPaths(entry, `${path}.${key}`);
  }
}

/** Produce the module source from the export HTML string — the pure core (no IO). */
export function generateFromHtml(html: string): string {
  const course = extractCourse(extractScript(html));
  assertRelativeAssetPaths(course.units, 'units');
  assertRelativeAssetPaths(course.intro, 'intro');
  assertRelativeAssetPaths(course.modules, 'modules');
  return emitModule(course);
}

/** Read the export and produce the module source (the IO shell; the `--check` CLI verifies freshness). */
export function generate(htmlPath: string = EXPORT_HTML): string {
  return generateFromHtml(readFileSync(htmlPath, 'utf8'));
}

function main(): void {
  const check = process.argv.includes('--check');
  const generated = generate();
  if (check) {
    const current = readFileSync(OUTPUT_MODULE, 'utf8');
    if (current !== generated) {
      throw new Error(
        `course generate --check: ${OUTPUT_MODULE} is stale; re-run \`pnpm tsx scripts/generate-course.ts\``,
      );
    }
    process.stdout.write('course generate --check: up to date\n');
    return;
  }
  writeFileSync(OUTPUT_MODULE, generated);
  process.stdout.write(`course generate: wrote ${OUTPUT_MODULE}\n`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
